export const jobs = [
  {
    period: "Jun 2026 — Present",
    role: "Technical Specialist, Network & Connectivity",
    company: "GEXEL Telecom International",
    type: "Montréal, QC",
    current: true,
    impacts: [
      "Root-cause Analysis",
      "Diagnostic Telemetry",
      "Technical Communication",
    ],
    points: [
      "Apply systematic root-cause analysis to diagnostic telemetry — signal strength, throughput, line quality, and error rates — to isolate faults across hardware, configuration, and infrastructure layers.",
      "Identify recurring fault signatures to accelerate triage and communicate technical diagnoses clearly to non-technical users.",
      "Operate within PCI-DSS-compliant systems under strict data-handling and access-control protocols.",
    ],
    tech: [
      "Network Diagnostics",
      "Telemetry Analysis",
      "Root-cause Analysis",
      "Access Control",
      "Technical Support",
    ],
  },
  {
    period: "Jul 2023 — Jun 2024",
    role: "Data Science Intern",
    company: "Blue Data Consulting",
    type: "Surat, Gujarat, India",
    impacts: ["−68% Gen. Time", "92% Accuracy", "+30% Consistency"],
    points: [
      "Built an end-to-end AI content generation system converting client descriptions into structured text, audio, and video using LLMs, LangChain, and Azure Cognitive Services.",
      "Engineered a production TTS + video generation workflow with Azure Speech + Video Indexer APIs — cutting generation time from 25 → 8 minutes (−68%) at 92% accuracy.",
      "Collaborated with engineering and business stakeholders in iterative sprint cycles, translating requirements into model and pipeline changes.",
      "Integrated feedback-driven prompt refinement and MLflow-tracked quality scoring, improving generative consistency by 30% across production use cases.",
    ],
    tech: [
      "Python",
      "LangChain",
      "Azure Speech API",
      "Azure Video Indexer",
      "MLflow",
      "LLMs",
    ],
  },
  {
    period: "Feb 2023 — May 2023",
    role: "Data Analyst / Data Science Intern",
    company: "The Sparks Foundation",
    type: "Remote",
    impacts: ["EDA & Modeling", "Weekly Dashboards", "Supervised ML"],
    points: [
      "Performed exploratory data analysis, predictive modeling, and visualization using Pandas, NumPy, and Scikit-learn to convert raw datasets into actionable business insights.",
      "Applied feature engineering, rigorous data cleaning, and quality control to tabular datasets before supervised modeling.",
      "Delivered weekly analytical reports and dashboards summarizing key business metrics, applying statistical analysis and supervised learning to support data-driven decisions.",
    ],
    tech: [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
    ],
  },
  {
    period: "Sep 2022 — Feb 2023",
    role: "Full Stack Developer Intern",
    company: "DevTown",
    type: "Remote",
    impacts: ["+83% Users", "−45% Errors", "+40% Speed"],
    points: [
      "Delivered a MERN-stack portal for an ed-tech client, growing active users from 120 → 220 (+83%) through interactive dashboards.",
      "Built secure Node.js/Express REST APIs with JWT authentication, reducing backend errors by 45% and improving load speed by 40%.",
    ],
    tech: ["React.js", "Node.js", "Express.js", "MongoDB", "JWT"],
  },
];
