export const jobs = [
  {
    period: "May 2026 — Present",
    role: "Software Developer",
    company: "Kofax",
    type: "Canada",
    current: true,
    impacts: ["1M+ Records", "+20% Automation", "30+ Issues Resolved"],
    points: [
      "Develop and maintain Python- and FastAPI-based backend services supporting enterprise workflows and processing 1M+ records, implementing reusable business logic, validation, transformation, and exception-handling components.",
      "Design and integrate REST APIs and JSON-based services across 10+ enterprise sources, implementing authentication, request/response handling, payload validation, error handling, and integration workflows.",
      "Develop AI-enabled backend capabilities using LLM APIs, embeddings, and RAG patterns to support context-aware information retrieval and intelligent application workflows.",
      "Build reusable Python automation components for recurring application workflows, reducing manual intervention by approximately 20% and improving execution consistency across operational processes.",
      "Develop and execute pytest-based unit and integration tests covering API endpoints, business logic, validation rules, exception scenarios, and regression cases; support Docker-based application environments and CI/CD workflows through Git and Azure DevOps.",
      "Troubleshoot and resolve 30+ application, API integration, and processing issues using SQL diagnostics, execution logs, API responses, automated test results, and root-cause analysis, collaborating with engineering teams on corrective solutions.",
      "Support Agile/Scrum delivery through requirements refinement, development coordination, UAT, defect resolution, release support, technical documentation, and production troubleshooting.",
    ],
    tech: [
      "Python",
      "FastAPI",
      "REST APIs",
      "Docker",
      "pytest",
      "CI/CD",
      "Azure DevOps",
      "LLM APIs",
      "RAG",
    ],
  },
  {
    period: "Sep 2025 — Apr 2026",
    role: "Software Developer Intern",
    company: "Coupa Software",
    type: "Canada",
    impacts: ["500K+ Records", "+15% Automation", "25+ Issues Resolved"],
    points: [
      "Developed Python- and SQL-based backend workflows for processing and validating 500K+ enterprise records, implementing reusable transformation, validation, and business-rule components.",
      "Integrated REST APIs and JSON services to support enterprise application workflows, handling authentication, request/response processing, malformed payloads, rate-limit conditions, and integration exceptions.",
      "Developed 3+ Python automation workflows, reducing recurring manual processing activities by approximately 15% while improving execution consistency and workflow reliability.",
      "Implemented pytest-based unit and integration testing for application logic, API integrations, validation rules, and exception scenarios; supported Docker-based development and testing environments.",
      "Supported CI/CD workflows through Git and Azure DevOps, contributing to automated validation, build checks, defect fixes, and controlled application delivery.",
      "Investigated 25+ application and API integration issues using logs, API responses, SQL diagnostics, test results, and root-cause analysis, resolving authentication, malformed-payload, and integration failures.",
      "Performed UAT and structured application testing against functional requirements, documenting expected versus actual behavior, reproducing defects, and coordinating fixes with development and business teams.",
    ],
    tech: ["Python", "SQL", "REST APIs", "Docker", "pytest", "Git", "Azure DevOps"],
  },
  {
    period: "Sep 2022 — Aug 2024",
    role: "Software Developer",
    company: "Advanced",
    type: "India",
    impacts: ["2M+ Records", "10+ Workflows", "100+ UAT Scenarios"],
    points: [
      "Developed Python- and SQL-driven application solutions supporting 2M+ enterprise records, implementing complex joins, CTEs, aggregations, transformation logic, validation, and application business rules.",
      "Designed and refined 10+ enterprise application workflows, analyzing functional requirements, system dependencies, integration points, automation opportunities, and enhancement requirements.",
      "Developed backend automation and API workflows to support application integration, data processing, validation, and exception handling across enterprise systems.",
      "Implemented pytest-based unit and integration testing for application logic, API workflows, data-processing components, and regression scenarios; used Docker to standardize application development and testing environments.",
      "Supported CI/CD-enabled software delivery using Git and development pipeline practices, contributing to automated validation, defect resolution, release readiness, and post-release support.",
      "Translated requirements from 20+ business stakeholders into functional specifications, user stories, acceptance criteria, application requirements, and implementation-ready technical documentation.",
      "Developed and maintained 30+ BRDs, FRDs, functional specifications, process flows, and technical documents, establishing traceability between requirements and delivered software functionality.",
      "Supported 100+ UAT scenarios and production troubleshooting, using SQL diagnostics, execution logs, validation checks, and root-cause analysis to identify and resolve application and workflow issues.",
    ],
    tech: ["Python", "SQL", "Docker", "pytest", "Git", "CI/CD"],
  },
];
